name: Docker Image cordova

on:
  push:
    branches: 
    - master   
    paths:
    - cordova/**
  pull_request:
    branches: 
    - master   
    paths:
    - cordova/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Build cordova docker image
      run: docker build cordova -t p0l0us/cordova:7.1.0-ant-gradle
    - name: Publish cordova docker image
      run: docker push p0l0us/cordova:7.1.0-ant-gradle
