name: Docker Image node

on:
  push:
    branches:
    - master
    paths:
    - node/**
  pull_request:
    branches:
    - master
    paths:
    - node/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
      
    - name: Build node docker image
      run: docker build node -t p0l0us/haxe:3.4-node-carbon-alpine
    - name: Publish node docker image
      run: docker push p0l0us/haxe:3.4-node-carbon-alpine
