name: Docker Image Tizen

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - name: Build tizen docker image
      run: docker build tizen -t p0l0us/haxe:tizen-cli-stretch
    - name: Publish tizen docker image
      run: docker push p0l0us/haxe:tizen-cli-stretch

